### ISSUE TITLE
It is not possible to download the file if the plugin is active

### ISSUE THREAD

**Issue by mrkohan** [moderntribe/weglot-companion#19]
Hello, I have a plugin to convert WordPress pages to PDF that conflict with this plugin. When this plugin is active, I can't export PDF from my pages.
What can I do to fix this problem?

**Comment by defunctl** [comment]
Hey @mrkohan,

This is a plugin we use internally for clients, so support is extremely limited.

1. Which process did you use to install this plugin?
2. Could you provide more detail and any relevant server logs, PHP/HTTP error messages?

Thanks

**Comment by mrkohan** [comment]
Thanks for your reply,
To convert wordpress pages to PDF, I use the e2pdf plugin.

you can check the sample page [here](https://partners.ecenglish.com/accommodation/cambridge-homestay/) select "export PDF" to see it
 [Also, this is the file's direct address](https://partners.ecenglish.com/pdf/e8b4d559cc273bb72e9c54e165020687/)

**Comment by defunctl** [comment]
Hi @mrkohan,

You didn't answer question number 1. Please let me know.

**Comment by mrkohan** [comment]
> * Which process did you use to install this plugin?

The plugin was installed directly from wordpress [repository](https://wordpress.org/plugins/weglot/) and the api key from the setup tab was copied to the plugin. Our project's owner plan is "Advanced."

**Comment by defunctl** [comment]
I think you may be confused, this plugin has no direct relation to the WeGlot company. This is a plugin developed by [Modern Tribe](https://tri.be/) for use with our clients and just extends the WeGlot plugin's functionality.

You'll want to contact the company's support directly: https://weglot.com/.
